### ISSUE TITLE
Install dependencies not up to date

### ISSUE THREAD

**Issue by DanRZ** [tbattz/iracingOverlay#1]
CMake must be updated to last version on master branch :
In CMakeLists.txt : cmake_minimum_required(VERSION 3.10)
In Installer part 1 : cmake-3.7.1-win64-x64.msi

The latest CMake release 3.20.1 works fine
https://github.com/Kitware/CMake/releases/download/v3.20.1/cmake-3.20.1-windows-x86_64.msi

Also, rename .bat files : ...Dependicies....bat > ...Dependencies....bat

**Comment by tbattz** [comment]
I've updated the minimum required cmake version to 3.15, as that's what I've got installed, which compiles and runs fine. I've set the installer to download the latest cmake version as of the time of writing this, 3.20.1. Tested and this seems to work too.

I've also merged some further features in changes that I had sitting on the deltas branch, which adds a +/- coloured delta line, which represents the gradient of your time delta. I.e. purple segments you're gaining time on your best lap, yellow you're losing time.

There was more that I was trying to do that's half implemented and in there, but not fully finished. I.e. a live track map (idea being you would colour sections of the map where you're gaining losing time, but I never got far enough to implement the colouring) and input from a steering wheel to toggle telemetry information. While I don't have the time to continue with that, some of the core structure that would enable someone to, is partially implemented in those changes.

Currently merged the fixes into master, see https://github.com/tbattz/iracingOverlay/commit/6b2808d27cfa666cbf56d7de9bf438f77d32e774 and commits before that.

**Comment by DanRZ** [comment]
Thanks for that. 

Installers/installDependiciesWindows-partX.bat are still not correctly renamed ... 👎 

And i found another bug in the step 1.

Replace  the line : 
"%UserProfile%\Downloads\wget.exe" --no-check-certificate http://gnuwin32.sourceforge.net/downlinks/make.php
By : 
"%UserProfile%\Downloads\wget.exe" **-O make-3.81.exe** --no-check-certificate http://gnuwin32.sourceforge.net/downlinks/make.php

If i don't add the -O option to wget.exe, i get a file named make.php which cannot be executed.

**Comment by tbattz** [comment]
Didn't realise what you were trying to say originally with the renaming, but I now realise it's spelt wrong. I'll fix it tomorrow evening.

Also realised I fixed a few of these issues in the updated version of openGLPlotLive a little while ago, but didn't update here. I'll pull the other changes into here tomorrow too. In the meantime if you have more trouble with the installers, see those changes here https://github.com/tbattz/openGLPlotLive/commit/de3f171341946aaedc413c6003037f30b02383cb

**Comment by tbattz** [comment]
Okay, I think I've fixed it in both the openGLPlotLive repo, and this project. The submodule now points to a branch dedicated to iracingOverlay, as the main repository code has moved on quite a bit since then.

See commits 3d00c0de588c68d0e5889ea5a2907be7bd8a8618, and ed992e87c6421092212c5a48c23a44fe7fa19723 in iracingOverlay, which are now on master, and in openGLPlotLive, see https://github.com/tbattz/openGLPlotLive/commit/f5c8fb5cdebc8b295628e41a1d5b0a025735995b and https://github.com/tbattz/openGLPlotLive/commit/8d42196c1dcc91c9a18889f3344b81c40b14d255 which should be included in the commit the submodule points to.

You might need to do a git submodule update due to the changes in openGLPlotLive.
